; SmartGarden — Irrigator Node (PoC v0.2)
; Hardware: LILYGO T3_V1.6.1 (ESP32 + SX1276)
;           IRLZ44N Low-Side-Switch (Pumpe), kapazitiver Bodenfeuchtesensor
; Funktion: Bodenfeuchte messen → Pumpe feuchtegesteuert schalten
;           → Status per LoRaWAN an TTN melden

[env:ttgo-lora32-v21]
platform  = espressif32
board     = ttgo-lora32-v21
framework = arduino

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder
upload_speed    = 921600

lib_deps =
    mcci-catena/MCCI LoRaWAN LMIC library @ ^4.1.1

build_flags =
    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS
    -D CFG_eu868=1
    -D CFG_sx1276_radio=1
    -D LMIC_ENABLE_arbitrary_clock_error=1
    -D hal_init=LMIC_HAL_init
